# Generated by Django 4.0.1 on 2022-01-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_document_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
